FROM java:8

LABEL key="Mohammad Zaman mazaman.aws@gmail.com"

ADD target/productservice-0.0.1-SNAPSHOT.jar productservice-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java", "-jar", "productservice-0.0.1-SNAPSHOT.jar"]

#WORKDIR
#RUN 
#CMD